/**
 * Column mapping for the SQLite Repository.
 *
 * The Sheets-backed handlers read and write rows where every key is camelCase
 * (`organizationId`, `createdAt`, …). The SQLite schema in
 * `db/migrations/001-initial-schema.sql` uses snake_case columns to follow
 * SQL convention (`organization_id`, `created_at`, …).
 *
 * This file is the single source of truth that bridges the two worlds:
 *
 *   - Each table lists every camelCase key the handlers use, mapped to the
 *     snake_case column it lives in.
 *   - SELECT aliases the snake_case column to the camelCase name so handlers
 *     can keep reading `row['organizationId']`.
 *   - INSERT/UPDATE rewrites the camelCase record keys to snake_case columns.
 *
 * Add a new table here when introducing a migration that adds tables. Do NOT
 * list `_mayordomia_migrations` here — it's managed by the migrator, not the
 * Repository.
 */
export interface ColumnMap {
  readonly [camelKey: string]: string; // camelCase → snake_case
}

export const COLUMNS: Record<string, ColumnMap> = {
  organizations: {
    id: 'id',
    name: 'name',
    timezone: 'timezone',
    active: 'active',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    version: 'version',
  },
  sites: {
    id: 'id',
    organizationId: 'organization_id',
    name: 'name',
    address: 'address',
    active: 'active',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    version: 'version',
  },
  users: {
    id: 'id',
    organizationId: 'organization_id',
    email: 'email',
    name: 'name',
    status: 'status',
    picture: 'picture',
    passwordHash: 'password_hash',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    version: 'version',
  },
  roles: {
    id: 'id',
    organizationId: 'organization_id',
    name: 'name',
    permissionIds: 'permission_ids',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    version: 'version',
  },
  user_roles: {
    userId: 'user_id',
    roleId: 'role_id',
    organizationId: 'organization_id',
    createdAt: 'created_at',
  },
  role_permissions: {
    roleId: 'role_id',
    organizationId: 'organization_id',
    permission: 'permission',
  },
  public_access_tokens: {
    token: 'token',
    organizationId: 'organization_id',
    expiresAt: 'expires_at',
    consumedAt: 'consumed_at',
    createdAt: 'created_at',
  },
  locations: {
    id: 'id',
    organizationId: 'organization_id',
    name: 'name',
    kind: 'kind',
    address: 'address',
    active: 'active',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    version: 'version',
  },
  resources: {
    id: 'id',
    organizationId: 'organization_id',
    kind: 'kind',
    name: 'name',
    status: 'status',
    locationId: 'location_id',
    siteId: 'site_id',
    metadata: 'metadata',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    version: 'version',
  },
  deliveries: {
    id: 'id',
    organizationId: 'organization_id',
    requestId: 'request_id',
    deliveredBy: 'delivered_by',
    deliveredTo: 'delivered_to',
    notes: 'notes',
    status: 'status',
    deliveredAt: 'delivered_at',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    createdBy: 'created_by',
    updatedBy: 'updated_by',
    version: 'version',
  },
  delivery_items: {
    id: 'id',
    organizationId: 'organization_id',
    deliveryId: 'delivery_id',
    resourceId: 'resource_id',
    quantity: 'quantity',
    notes: 'notes',
    createdAt: 'created_at',
    version: 'version',
  },
  maintenance: {
    id: 'id',
    organizationId: 'organization_id',
    resourceId: 'resource_id',
    source: 'source',
    severity: 'severity',
    status: 'status',
    title: 'title',
    description: 'description',
    openedAt: 'opened_at',
    closedAt: 'closed_at',
    assignedTo: 'assigned_to',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    createdBy: 'created_by',
    updatedBy: 'updated_by',
    version: 'version',
  },
  maintenance_updates: {
    id: 'id',
    organizationId: 'organization_id',
    maintenanceId: 'maintenance_id',
    author: 'author',
    comment: 'comment',
    statusAfter: 'status_after',
    createdAt: 'created_at',
    version: 'version',
  },
  requests: {
    id: 'id',
    organizationId: 'organization_id',
    siteId: 'site_id',
    type: 'type',
    kind: 'kind',
    requesterName: 'requester_name',
    requesterEmail: 'requester_email',
    description: 'description',
    requestedFor: 'requested_for',
    source: 'source',
    status: 'status',
    eventStart: 'event_start',
    eventEnd: 'event_end',
    urgencyReason: 'urgency_reason',
    lateReason: 'late_reason',
    currentArea: 'current_area',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    createdBy: 'created_by',
    updatedBy: 'updated_by',
    version: 'version',
  },
  request_approvals: {
    id: 'id',
    organizationId: 'organization_id',
    requestId: 'request_id',
    scope: 'scope',
    areaId: 'area_id',
    status: 'status',
    reviewedBy: 'reviewed_by',
    reviewedAt: 'reviewed_at',
    comment: 'comment',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    updatedBy: 'updated_by',
    version: 'version',
  },
  events: {
    id: 'id',
    organizationId: 'organization_id',
    siteId: 'site_id',
    name: 'name',
    description: 'description',
    startsAt: 'starts_at',
    endsAt: 'ends_at',
    status: 'status',
    calendarEventId: 'calendar_event_id',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    createdBy: 'created_by',
    updatedBy: 'updated_by',
    version: 'version',
  },
  event_areas: {
    eventId: 'event_id',
    areaId: 'area_id',
    organizationId: 'organization_id',
  },
  event_resources: {
    eventId: 'event_id',
    resourceId: 'resource_id',
    organizationId: 'organization_id',
    quantity: 'quantity',
  },
  suppliers: {
    id: 'id',
    organizationId: 'organization_id',
    name: 'name',
    contact: 'contact',
    notes: 'notes',
    active: 'active',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    version: 'version',
  },
  purchase_requests: {
    id: 'id',
    organizationId: 'organization_id',
    supplierId: 'supplier_id',
    status: 'status',
    justification: 'justification',
    decision: 'decision',
    decidedBy: 'decided_by',
    decidedAt: 'decided_at',
    totalEstimated: 'total_estimated',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    createdBy: 'created_by',
    updatedBy: 'updated_by',
    version: 'version',
  },
  purchase_request_items: {
    id: 'id',
    organizationId: 'organization_id',
    purchaseRequestId: 'purchase_request_id',
    description: 'description',
    quantity: 'quantity',
    unitPrice: 'unit_price',
    notes: 'notes',
    createdAt: 'created_at',
    version: 'version',
  },
  quotes: {
    id: 'id',
    organizationId: 'organization_id',
    purchaseRequestId: 'purchase_request_id',
    supplierId: 'supplier_id',
    total: 'total',
    notes: 'notes',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    version: 'version',
  },
  notifications: {
    id: 'id',
    organizationId: 'organization_id',
    targetUserId: 'target_user_id',
    kind: 'kind',
    title: 'title',
    body: 'body',
    payload: 'payload',
    readAt: 'read_at',
    createdAt: 'created_at',
  },
  sessions: {
    id: 'id',
    userId: 'user_id',
    organizationId: 'organization_id',
    expiresAt: 'expires_at',
    revokedAt: 'revoked_at',
    createdAt: 'created_at',
    userAgent: 'user_agent',
    ip: 'ip',
  },
  magic_link_tokens: {
    tokenHash: 'token_hash',
    userId: 'user_id',
    organizationId: 'organization_id',
    expiresAt: 'expires_at',
    consumedAt: 'consumed_at',
    createdAt: 'created_at',
  },
  webauthn_credentials: {
    credentialId: 'credential_id',
    userId: 'user_id',
    organizationId: 'organization_id',
    publicKey: 'public_key',
    counter: 'counter',
    transports: 'transports',
    createdAt: 'created_at',
    lastUsedAt: 'last_used_at',
  },
  webauthn_challenges: {
    challenge: 'challenge',
    userId: 'user_id',
    organizationId: 'organization_id',
    purpose: 'purpose',
    expiresAt: 'expires_at',
    createdAt: 'created_at',
  },
  audit_log: {
    id: 'id',
    organizationId: 'organization_id',
    actorId: 'actor_id',
    action: 'action',
    entity: 'entity',
    entityId: 'entity_id',
    payload: 'payload',
    at: 'at',
  },
};

export function columnMapFor(table: string): ColumnMap {
  const map = COLUMNS[table];
  if (!map) {
    throw new Error(`Repository: unknown table "${table}". Add it to COLUMNS.`);
  }
  return map;
}
