import { useState } from 'react';
import { ArrowBack, ArrowForward, Build, Campaign, Chair, Inventory2, OtherHouses, VolumeUp } from '@mui/icons-material';
import { Alert, Box, Button, Card, CardActionArea, CardContent, Container, LinearProgress, MenuItem, Stack, TextField, Typography } from '@mui/material';

const requestTypes = [{ key: 'RESOURCE', label: 'Solicitar recursos', icon: Inventory2 }, { key: 'LOCATION', label: 'Reservar un espacio', icon: Chair }, { key: 'AUDIO', label: 'Solicitar sonido', icon: VolumeUp }, { key: 'MULTIMEDIA', label: 'Solicitar multimedia', icon: Campaign }, { key: 'MAINTENANCE', label: 'Reportar un problema', icon: Build }, { key: 'OTHER', label: 'Otro', icon: OtherHouses }];

export function PublicRequestPage() {
  const params = new URLSearchParams(location.search); const preset = params.get('area');
  const [step, setStep] = useState(preset ? 1 : 0); const [type, setType] = useState(preset?.toUpperCase() ?? ''); const [sent, setSent] = useState(false);
  if (sent) return <Container maxWidth="sm" sx={{ py: 8 }}><Card><CardContent sx={{ textAlign: 'center', py: 6 }}><Typography fontSize="3rem">✓</Typography><Typography variant="h1">Solicitud recibida</Typography><Typography color="text.secondary" mt={2}>Guardá este código para consultar el estado.</Typography><Typography variant="h2" color="primary" mt={2}>SOL-2026-00143</Typography></CardContent></Card></Container>;
  return <Container maxWidth="sm" sx={{ py: { xs: 3, sm: 6 } }}><Stack spacing={3}>
    <Box textAlign="center"><Typography variant="h1" color="primary">Mayordomía</Typography><Typography color="text.secondary">Organización para servir</Typography></Box><LinearProgress variant="determinate" value={((step + 1) / 4) * 100} aria-label={`Paso ${step + 1} de 4`} />
    {step === 0 && <><Box><Typography variant="h2">¿En qué podemos ayudarte?</Typography><Typography color="text.secondary">Elegí una opción para empezar.</Typography></Box><Stack gap={1}>{requestTypes.map(item => <Card key={item.key} variant={type === item.key ? 'outlined' : undefined}><CardActionArea onClick={() => { setType(item.key); setStep(1); }}><CardContent sx={{ display: 'flex', alignItems: 'center', gap: 2 }}><item.icon color="primary" /><Typography fontWeight={700}>{item.label}</Typography></CardContent></CardActionArea></Card>)}</Stack></>}
    {step === 1 && <Stack gap={2}><Typography variant="h2">¿Para qué lo necesitás?</Typography><TextField required label="Tu nombre" autoComplete="name" /><TextField required label="Teléfono o email" autoComplete="email" /><TextField required label="Evento o motivo" /><TextField select label="Cantidad estimada de personas" defaultValue="1-25"><MenuItem value="1-25">1–25</MenuItem><MenuItem value="26-100">26–100</MenuItem><MenuItem value="100+">Más de 100</MenuItem></TextField></Stack>}
    {step === 2 && <Stack gap={2}><Typography variant="h2">¿Cuándo y dónde?</Typography><TextField required type="date" label="Fecha" slotProps={{ inputLabel: { shrink: true } }} /><Stack direction="row" gap={1}><TextField fullWidth required type="time" label="Desde" slotProps={{ inputLabel: { shrink: true } }} /><TextField fullWidth required type="time" label="Hasta" slotProps={{ inputLabel: { shrink: true } }} /></Stack><TextField label="Espacio" placeholder="Salón principal" /><Alert severity="info">Las solicitudes deberían enviarse con 7 días de anticipación. Si es urgente, explicá el motivo.</Alert></Stack>}
    {step === 3 && <Stack gap={2}><Typography variant="h2">Detalles y confirmación</Typography><TextField multiline minRows={4} label="¿Qué necesitás exactamente?" /><TextField label="Motivo de urgencia (si corresponde)" /><Box sx={{ position: 'absolute', left: '-10000px' }}><TextField label="Sitio web" name="website" tabIndex={-1} /></Box><Alert severity="success">Revisá los datos. Al enviar recibirás un código de seguimiento.</Alert></Stack>}
    {step > 0 && <Stack direction="row" justifyContent="space-between"><Button startIcon={<ArrowBack />} onClick={() => setStep(step - 1)}>Atrás</Button>{step < 3 ? <Button variant="contained" endIcon={<ArrowForward />} onClick={() => setStep(step + 1)}>Continuar</Button> : <Button variant="contained" onClick={() => setSent(true)} disabled={!type}>Enviar solicitud</Button>}</Stack>}
  </Stack></Container>;
}
