import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { registerSW } from 'virtual:pwa-register';
import { App } from './app/App';
import { theme } from './app/theme';
import { AuthContextProvider, GoogleIdentityAuthProvider } from './integrations/auth';
import {
  createBootstrapClient,
  CurrentOrgProvider,
  OrgProvider,
  useCurrentOrg,
} from './integrations/org';
import { DataProvider } from './integrations/data';
import './app/global.css';

/**
 * GitHub Pages serves `404.html` (generated by vite-plugin-pwa) when an
 * unknown path is requested. That page stashes the original URL in
 * `sessionStorage.redirect` and bounces the browser to the SPA root.
 * Before React Router takes over, replay the stashed URL so deep links
 * like `/Mayordomia/solicitar` resolve to `/solicitar` inside the SPA.
 *
 * Runs only in production builds (no-op when sessionStorage is empty
 * or unavailable, e.g. during local dev with no 404 fallback).
 */
function replayGhPagesRedirect(): void {
  try {
    const target = sessionStorage.getItem('redirect');
    if (!target) return;
    sessionStorage.removeItem('redirect');
    const url = new URL(target);
    // Stay on the same origin (don't follow a different host) and use
    // replaceState so the redirect hop doesn't pollute browser history.
    if (url.origin === window.location.origin) {
      window.history.replaceState(null, '', url.pathname + url.search + url.hash);
    }
  } catch {
    /* sessionStorage unavailable (SSR, private mode, sandboxed iframe). */
  }
}
replayGhPagesRedirect();

registerSW({ immediate: true });
const queryClient = new QueryClient({
  defaultOptions: { queries: { staleTime: 30_000, retry: 1 } },
});

const googleClientId = import.meta.env.VITE_GOOGLE_CLIENT_ID ?? '';
const appsScriptUrl = import.meta.env.VITE_APPS_SCRIPT_URL ?? '';
const useMockPublic = import.meta.env.VITE_USE_MOCK_PUBLIC === 'true';

const authProvider = new GoogleIdentityAuthProvider({ clientId: googleClientId });
const bootstrapClient = createBootstrapClient({
  appsScriptUrl,
  getAccessToken: () => authProvider.getValidAccessToken(),
  mock: useMockPublic || !appsScriptUrl,
});

const gatewayDeps = {
  appsScriptUrl,
  getAccessToken: () => authProvider.getValidAccessToken(),
  mock: useMockPublic || !appsScriptUrl,
};

function InnerProviders({ children }: { children: React.ReactNode }) {
  const { organizationId, ready } = useCurrentOrg();
  if (!ready || !organizationId) {
    // While discovery is loading or the user has no org yet, render the app
    // without a DataProvider. Modules that need data will show their own
    // empty state.
    return <>{children}</>;
  }
  return (
    <DataProvider deps={gatewayDeps} organizationId={organizationId}>
      {children}
    </DataProvider>
  );
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <QueryClientProvider client={queryClient}>
        <AuthContextProvider provider={authProvider}>
          <OrgProvider client={bootstrapClient}>
            <CurrentOrgProvider>
              <InnerProviders>
                <BrowserRouter basename={import.meta.env.BASE_URL}>
                  <App />
                </BrowserRouter>
              </InnerProviders>
            </CurrentOrgProvider>
          </OrgProvider>
        </AuthContextProvider>
      </QueryClientProvider>
    </ThemeProvider>
  </React.StrictMode>,
);
