import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { registerSW } from 'virtual:pwa-register';
import { App } from './app/App';
import { theme } from './app/theme';
import { AuthContextProvider, LocalAuthProvider } from './integrations/auth';
import {
  createBootstrapClient,
  CurrentOrgProvider,
  OrgProvider,
  useCurrentOrg,
} from './integrations/org';
import { DataProvider } from './integrations/data';
import './app/global.css';

/**
 * GitHub Pages serves `404.html` (generated by vite-plugin-pwa) when an
 * unknown path is requested. That page stashes the original URL in
 * `sessionStorage.redirect` and bounces the browser to the SPA root.
 * Before React Router takes over, replay the stashed URL so deep links
 * like `/Mayordomia/solicitar` resolve to `/solicitar` inside the SPA.
 *
 * Runs only in production builds (no-op when sessionStorage is empty
 * or unavailable, e.g. during local dev with no 404 fallback).
 */
function replayGhPagesRedirect(): void {
  try {
    const target = sessionStorage.getItem('redirect');
    if (!target) return;
    sessionStorage.removeItem('redirect');
    const url = new URL(target);
    // Stay on the same origin (don't follow a different host) and use
    // replaceState so the redirect hop doesn't pollute browser history.
    if (url.origin === window.location.origin) {
      window.history.replaceState(null, '', url.pathname + url.search + url.hash);
    }
  } catch {
    /* sessionStorage unavailable (SSR, private mode, sandboxed iframe). */
  }
}
replayGhPagesRedirect();

registerSW({ immediate: true });
const queryClient = new QueryClient({
  defaultOptions: { queries: { staleTime: 30_000, retry: 1 } },
});

const appsScriptUrl = import.meta.env.VITE_APPS_SCRIPT_URL ?? '';
const useMockPublic = import.meta.env.VITE_USE_MOCK_PUBLIC === 'true';

// PR 4: local email+password auth (replaces GoogleIdentityAuthProvider).
// The provider reads its base URL from the gateway URL; in dev with a
// Vite proxy that points at the local gateway, cookies work cross-origin.
const authProvider = new LocalAuthProvider({ baseUrl: appsScriptUrl });
const bootstrapClient = createBootstrapClient({
  appsScriptUrl,
  getAccessToken: () => authProvider.getValidAccessToken(),
  mock: useMockPublic || !appsScriptUrl,
});

const gatewayDeps = {
  appsScriptUrl,
  getAccessToken: () => authProvider.getValidAccessToken(),
  mock: useMockPublic || !appsScriptUrl,
};

function InnerProviders({ children }: { children: React.ReactNode }) {
  const { organizationId, ready } = useCurrentOrg();
  // Always wrap with a DataProvider, even before org discovery settles or
  // when the user has no org yet. Components like <NotificationBell> that
  // live in <AppShell> hook into the DataContext on every render and
  // crash the whole tree if the provider is absent. Clients in mock mode
  // return empty/loading states without a real org, so this is safe.
  // We pass an empty string when no org is bound; hooks gate their
  // requests on `!!organizationId`, so nothing fires.
  return (
    <DataProvider deps={gatewayDeps} organizationId={ready && organizationId ? organizationId : ''}>
      {children}
    </DataProvider>
  );
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <QueryClientProvider client={queryClient}>
        <AuthContextProvider provider={authProvider}>
          <OrgProvider client={bootstrapClient}>
            <CurrentOrgProvider>
              <InnerProviders>
                <BrowserRouter basename={import.meta.env.BASE_URL}>
                  <App />
                </BrowserRouter>
              </InnerProviders>
            </CurrentOrgProvider>
          </OrgProvider>
        </AuthContextProvider>
      </QueryClientProvider>
    </ThemeProvider>
  </React.StrictMode>,
);
